### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by majidaldo** [digitalbazaar/pyld#173]
project seems abandoned. should be noted as such.

**Comment by dlongley** [comment]
This project is not abandoned. The maintainers work on a lot of different projects and prioritize accordingly.

I noted that you filed an issue requesting that someone implement JSON-LD star here: #172. We don't plan on implementing that community draft report (not yet a standard or a spec at W3C's CR level) at this time. It's also not clear if it should be implemented in this library. If you'd prefer, we can close that issue with a link to this comment.

I'm closing this issue because we will not be adding the requested note for the above reasons.

**Comment by majidaldo** [comment]
thanks for the note.

last commit was three years ago with plenty of issues since then. that's why i assumed it was abandoned.

**Comment by davidlehn** [comment]
Help wanted. :-)
There used to be near parity between our js an py libraries, but we unfortunately haven't had the time and resources to keep the py code up to date.

**Comment by majidaldo** [comment]
> Help wanted. :-) There used to be near parity between our js an py libraries, but we unfortunately haven't had the time and resources to keep the py code up to date.

i wonder if you can just interface js.
